enum CommandName {
  undo,
  redo,
  foreColor,
  backColor,
  fontName,
  fontSize,
  bold,
  italic,
  underline,
  subscript,
  superscript,
  strikeThrough,
  formatBlock, // passes value for below format
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  p,
  pre,
  br, // not settable (at least i don't know how)
  blockQuote,
  removeFormat,
  justifyCenter,
  justifyFull,
  justifyLeft,
  justifyRight,
  indent,
  outdent,
  insertUnorderedList,
  insertOrderedList,
  insertHorizontalRule,
  insertHtml, // determines if the three command below are executable
  insertLink, // pseudo commands, there are no corresponding values for execCommand()
  insertImage,
  insertCheckbox,
// pseudo commands for toggling grouped command views
  expandingSearchViewing,
}
