# Basic analysis options for the rich_editor package
# Focuses on essential lints without being overly strict

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"
    - "example/build/**"
    - "example/ios/**"
    - "example/android/**"
    - "example/macos/**"
    - "example/web/**"
